/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:bee31048-3b12-42fd-b31b-16a224869862",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_8fZct8A30",
    "aws_user_pools_web_client_id": "11a2q1khet1kb64rqdu419f083",
    "oauth": {}
};


export default awsmobile;
